#!/usr/bin/env python3
"""Generate COVERAGE.md: the map of what WikiSyllabus has and where the gaps are.

Usage: python3 scripts/coverage.py   (writes COVERAGE.md in repo root)
"""
import os
from collections import defaultdict
from datetime import date

counts = defaultdict(lambda: defaultdict(set))  # uni -> branch -> {(year, sem)}
files_per_uni = defaultdict(int)

for root, _dirs, names in os.walk("universities"):
    for n in names:
        if not n.endswith(".md"):
            continue
        rel = os.path.relpath(os.path.join(root, n)).replace(os.sep, "/")
        parts = rel.split("/")
        if len(parts) == 6:
            _, uni, branch, year, sem, _f = parts
            counts[uni][branch].add((year, sem))
            files_per_uni[uni] += 1
        elif len(parts) > 1:
            files_per_uni[parts[1]] += 1

lines = [
    "# Coverage Map",
    "",
    f"*Auto-generated by `scripts/coverage.py` on {date.today().isoformat()}. "
    "Regenerate after adding content: `python3 scripts/coverage.py`*",
    "",
    "The gaps in this table are the contribution opportunities. "
    "Pick a hole, find the official syllabus, follow "
    "[CONTRIBUTION.md](./CONTRIBUTION.md).",
    "",
    "| University | Courses (files) | Branches | Scheme years | Semesters covered |",
    "|---|---|---|---|---|",
]

for uni in sorted(files_per_uni, key=files_per_uni.get, reverse=True):
    branches = counts[uni]
    years = sorted({y for b in branches.values() for (y, _s) in b})
    sems = sorted({s for b in branches.values() for (_y, s) in b})
    lines.append(
        f"| {uni} | {files_per_uni[uni]} | {len(branches)} | "
        f"{', '.join(years) if years else '-'} | "
        f"{', '.join(sems) if sems else '-'} |"
    )

total = sum(files_per_uni.values())
lines += [
    "",
    f"**Total: {total} syllabus files across {len(files_per_uni)} universities.**",
    "",
    "## Reading the gaps",
    "",
    "- A university with one branch needs its other branches (see issue #122)",
    "- A branch missing recent scheme years needs the current revision",
    "- Missing semesters within a scheme are the fastest wins",
    "- Universities requested by the community but absent here: see the open "
    "[Feature Request issues](https://github.com/The-Purple-Movement/WikiSyllabus/issues)",
]

with open("COVERAGE.md", "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"COVERAGE.md written: {total} files, {len(files_per_uni)} universities")
